default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host:     <%= ENV['DB_HOST'] %>

development:
  <<: *default

secondary:
  <<: *default
  database: <%= ENV['MBC_DB_NAME'] %>
  username: <%= ENV['MBC_DB_USER'] %>
  password: <%= ENV['MBC_DB_PASSWORD'] %>
  host: <%= ENV['MBC_DB_HOST'] %>
  
test:
  <<: *default
  database: mbc_backend_test

production:
  <<: *default