default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host:     <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || "mbc_dev" %>
  username: <%= ENV['DB_USER'] || "bliimo" %>
  password: <%= ENV['DB_PASSWORD'] || "password" %>
  host:     <%= ENV['DB_HOST'] || "localhost" %>

# development:
#   <<: *default
#   database: <%= ENV['DB_NAME'] || "mbc_development" %>
#   username: <%= ENV['DB_USER'] || "username" %>
#   password: <%= ENV['DB_PASSWORD'] || "password" %>
#   host:     <%= ENV['DB_HOST'] || "localhost" %>

secondary:
  <<: *default
  database: <%= ENV['MBC_DB_NAME'] || "mbc_api_dev" %>
  username: <%= ENV['MBC_DB_USER'] || "bliimodev" %>
  password: <%= ENV['MBC_DB_PASSWORD'] || "P@$$w0RD" %>
  host: <%= ENV['MBC_DB_HOST'] || "199.91.69.177" %>

test:
  <<: *default
  database: <%= ENV['DB_NAME'] || "mbc_test" %>
  username: <%= ENV['DB_USER'] || "username" %>
  password: <%= ENV['DB_PASSWORD'] || "password" %>
  host:     <%= ENV['DB_HOST'] || "localhost" %>

production:
  <<: *default